export {default as LoginAnimation} from "./LoginAnimation"
export {default as SignUpAnimation} from "./SignUpAnimation"
export {default as ReferAnimation} from "./ReferAnimation"
export {default as Animation} from "./Animation"
export {default as ContactAnimation} from "./Contact"
export {default as Loader} from "./Loader"