export {default as Home} from "./Home/Home"
export {default as Layout} from "./layout"
export {default as Property} from "./Property/Property"
export {default as PropertyDetail} from "./Property/PropertyDetail"
export {default as Login} from "./Login/Login"
export {default as Plans} from "./Normal/Plans"
export {default as AddProperty} from "./Property/AddProperty"